module.exports = {
    CI_REPO_OWNER: 'CI_REPO_OWNER_FILE',
    CI_REPO_NAME: 'CI_REPO_NAME_FILE',
    CI_COMMIT_SHA: 'CI_COMMIT_SHA_FILE',
    CI_BASE_BRANCH: 'CI_BASE_BRANCH_FILE',
    COMMIT_WATCH_OUTPUT_DIR: 'COMMIT_WATCH_OUTPUT_DIR_FILE',
    COMMIT_WATCH_OUTPUT_FILENAME: 'COMMIT_WATCH_OUTPUT_FILENAME_FILE',
    VERBOSE: 'VERBOSE_FILE',
}
