module.exports = {
    CI_REPO_OWNER: 'CI_REPO_OWNER_FILE',
    CI_REPO_NAME: 'CI_REPO_NAME_FILE',
    CI_COMMIT_SHA: 'CI_COMMIT_SHA_FILE',
    CI_BASE_BRANCH: 'CI_BASE_BRANCH_FILE',
    OUTPUT_DIR: 'OUTPUT_DIR_FILE',
    OUTPUT_FILENAME: 'OUTPUT_FILENAME_FILE',
    VERBOSE: 'VERBOSE_FILE',
}
