name: Commit Watch

on:
  - pull_request

env:
  CI: 1
  ARTIFACT_DIR: artifacts

jobs:
  commit_watch:
    name: Run Commit Watch
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v2
        - name: Run Commit Watch
          env:
            COMMIT_WATCH_OUTPUT_DIR: ${{ env.ARTIFACT_DIR }}/
            COMMITWATCH_GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            CI_REPO_OWNER: ${{ github.repository_owner }}
            CI_REPO_NAME: ${{ github.event.repository.name }}
            CI_BRANCH: ${{ github.head_ref }}
            CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
            CI_BASE_BRANCH: ${{ github.base_ref }}
            VERBOSE: 1
          run: git log origin/master
